# Variable
@base=http://localhost:3333
@useId={{LoginUser.response.body.user.id}}
@token={{LoginUser.response.body.token}}
@movieId={{GetAllWatchLaterMedias.response.body.watchLaterMedias[1].MovieId}}

### Read Hearth
# @name CheckHearth
GET {{base}}/hearth

### Create user
# @name CreateUser
POST {{base}}/users/register
Content-Type: application/json

{
  "name": "Matheus",
  "email": "ghome@gmail.com",
  "password": "Matheus123"
}

### Login user
# @name LoginUser
POST {{base}}/users/login
Content-Type: application/json

{
  "email": "ghome@gmail.com",
  "password": "Matheus123"
}

### Profile user
# @name ProfileUser
GET {{base}}/users/profile
Authorization: Bearer {{token}}

### Update user
# @name UpdateUserPhoto
PATCH {{base}}/users/update
Content-Type: multipart/form-data; boundary=----separate
Authorization: Bearer {{token}}

------separate
Content-Disposition: form-data; name="file"; filename="paimon.png"
Content-Type: image/png

< ./paimon.png
------separate
Content-Disposition: form-data; name="name"

matheus
------separate--

### Create Watch Later Medias
# @name CreateWatchLaterMedia
POST {{base}}/watch-later
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "MovieId": "tt93485",
  "image": "http://localhost:5679/exemple.com/movie.png",
  "title": "Ice Dragons",
  "release": 2007,
  "type": "movie"
}

### Get All Watch Later Medias
# @name GetAllWatchLaterMedias
GET {{base}}/watch-later
Authorization: Bearer {{token}}

### Get Watch Later Media
# @name GetWatchLaterMedia
GET {{base}}/watch-later/{{movieId}}
Authorization: Bearer {{token}}

### Delete Watch Later Media
# @name DeleteWatchLaterMedia
DELETE {{base}}/watch-later/{{movieId}}
Authorization: Bearer {{token}}

### Create Assessment Media
# @name CreateAssessmentMedia
POST {{base}}/assessment/{{movieId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "liked": true,
  "unlike": false
}

### Get Assessment Media
# @name GetAssessmentMedia
GET {{base}}/assessment/{{movieId}}
Authorization: Bearer {{token}}

### Update Assessment Media
# @name UpdateAssessmentMedia
PATCH  {{base}}/assessment/{{movieId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "liked": true,
  "unlike": false
}

